name: lidar3
channels:
  - pytorch-lts
  - anaconda
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - _tflow_select=2.3.0=mkl
  - aiohttp=3.7.4.post0=py38h7f8727e_2
  - astor=0.8.1=py38h06a4308_0
  - astunparse=1.6.3=py_0
  - async-timeout=3.0.1=py38h06a4308_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - autopep8=1.5.7=pyhd3eb1b0_0
  - blas=1.0=mkl
  - blinker=1.4=py38h06a4308_0
  - bottleneck=1.3.2=py38heb32a55_1
  - brotli=1.0.9=h7f98852_5
  - brotli-bin=1.0.9=h7f98852_5
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2021.9.30=h06a4308_1
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2021.10.8=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.1=pyhd3eb1b0_0
  - coverage=5.5=py38h27cfd23_2
  - cryptography=3.4.8=py38hd23ed53_0
  - cudatoolkit=11.1.74=h6bb024c_0
  - cycler=0.10.0=py_2
  - cython=0.29.24=py38h295c915_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - expat=2.4.1=h9c3ff4c_0
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.1=hba837de_1005
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-auth-oauthlib=0.4.4=pyhd3eb1b0_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=h28cd5cc_2
  - hdf5=1.10.6=hb1b8bf9_0
  - icu=58.2=hf484d3e_1000
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py38h06a4308_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jax=0.2.24=pyhd8ed1ab_0
  - jaxlib=0.1.73=py38h43a58ef_0
  - jpeg=9b=h024ee3a_2
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.3.1=py38h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libbrotlicommon=1.0.9=h7f98852_5
  - libbrotlidec=1.0.9=h7f98852_5
  - libbrotlienc=1.0.9=h7f98852_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libidn2=2.3.2=h7f8727e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.17.2=h4ff587b_1
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.32.1=h7f98852_1000
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.13=h7f98852_1003
  - libxml2=2.9.12=h03d6c58_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h295c915_1
  - markdown=3.3.4=py38h06a4308_0
  - matplotlib=3.4.3=py38h578d9bd_1
  - matplotlib-base=3.4.3=py38hbbc1b5f_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - multidict=5.1.0=py38h27cfd23_2
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numexpr=2.7.3=py38h22e1b3c_1
  - oauthlib=3.1.1=pyhd3eb1b0_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1l=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - pandas=1.3.3=py38h8c16a72_0
  - pcre=8.45=h9c3ff4c_0
  - pillow=8.4.0=py38h5aabda8_0
  - pip=21.2.4=py38h06a4308_0
  - protobuf=3.17.2=py38h295c915_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycodestyle=2.7.0=pyhd3eb1b0_0
  - pycparser=2.20=py_2
  - pyemd=0.5.1=py38hc5bc63f_1002
  - pyjwt=2.1.0=py38h06a4308_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py38h05f1152_4
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.2=py3.8_cuda11.1_cudnn8.0.5_0
  - pytz=2021.3=pyhd3eb1b0_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.6.2=py38had2a1c9_1
  - seaborn=0.11.0=py_0
  - setuptools=58.0.4=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow-estimator=2.6.0=pyh7b7c402_0
  - termcolor=1.1.0=py38h06a4308_1
  - tk=8.6.11=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - torchaudio=0.8.2=py38
  - torchvision=0.9.2=py38_cu111
  - tornado=6.1=py38h497a2fe_1
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - urllib3=1.26.7=pyhd3eb1b0_0
  - werkzeug=2.0.1=pyhd3eb1b0_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - wrapt=1.12.1=py38h7b6447c_1
  - x264=1!157.20191217=h7b6447c_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.5=h7b6447c_0
  - yarl=1.6.3=py38h27cfd23_0
  - zipp=3.6.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.10.0
    - addict==2.4.0
    - anyio==3.3.4
    - argon2-cffi==21.1.0
    - backcall==0.2.0
    - bleach==4.1.0
    - clang==5.0
    - contextlib2==21.6.0
    - debugpy==1.5.1
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - dill==0.3.4
    - dm-tree==0.1.6
    - entrypoints==0.3
    - flatbuffers==1.12
    - googleapis-common-protos==1.53.0
    - grpcio==1.41.0
    - h5py==3.1.0
    - ipykernel==6.4.2
    - ipython==7.28.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - jedi==0.18.0
    - joblib==1.1.0
    - json5==0.9.6
    - jsonschema==4.1.2
    - jupyter-client==7.0.6
    - jupyter-core==4.8.1
    - jupyter-packaging==0.11.0
    - jupyter-server==1.11.1
    - jupyterlab==3.2.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.8.2
    - jupyterlab-widgets==1.0.2
    - keras==2.6.0
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - ml-collections==0.1.0
    - nbclassic==0.3.3
    - nbclient==0.5.4
    - nbconvert==6.2.0
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.5
    - numpy==1.19.5
    - open3d==0.13.0
    - opencv-python==4.5.4.58
    - packaging==21.0
    - pandocfilters==1.5.0
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.11.0
    - promise==2.3
    - prompt-toolkit==3.0.21
    - ptyprocess==0.7.0
    - pygments==2.10.0
    - pyrsistent==0.18.0
    - pyyaml==6.0
    - pyzmq==22.3.0
    - requests-unixsocket==0.2.0
    - scikit-learn==1.0.1
    - send2trash==1.8.0
    - six==1.15.0
    - sniffio==1.2.0
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorflow==2.6.0
    - tensorflow-addons==0.12.0
    - tensorflow-datasets==3.2.0
    - tensorflow-gan==2.0.0
    - tensorflow-hub==0.12.0
    - tensorflow-io==0.21.0
    - tensorflow-io-gcs-filesystem==0.21.0
    - tensorflow-metadata==1.2.0
    - tensorflow-probability==0.14.1
    - terminado==0.12.1
    - testpath==0.5.0
    - threadpoolctl==3.0.0
    - tomlkit==0.7.2
    - torch-tb-profiler==0.3.1
    - traitlets==5.1.1
    - typeguard==2.13.0
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.2.1
    - widgetsnbextension==3.5.1
